const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');const mode=process.argv[2]||'after';const out=path.join(process.env.TEMP||require('os').tmpdir(),'cw-consent-ux',mode);fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let p=path.join(root,new URL(req.url,'http://localhost').pathname);if(fs.statSync(p).isDirectory())p=path.join(p,'index.html');res.setHeader('Content-Type',({'.css':'text/css','.js':'text/javascript','.html':'text/html','.svg':'image/svg+xml'})[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));});
(async()=>{await new Promise(r=>server.listen(8769,'127.0.0.1',r));const b=await chromium.launch({channel:'msedge',headless:true});let report=[];try{for(const width of [320,375,390,1440]){const ctx=await b.newContext({viewport:{width,height:width===1440?900:844},reducedMotion:'reduce'});if(mode==='before')await ctx.route('**/assets/consent.css',r=>r.fulfill({contentType:'text/css',body:require('child_process').execFileSync('git',['show','0f9afe5:assets/consent.css'],{cwd:root,encoding:'utf8'})}));await ctx.route('https://**/*',r=>r.fulfill({status:204}));const p=await ctx.newPage();await p.goto('http://127.0.0.1:8769/');await p.screenshot({path:path.join(out,`banner-${width}.png`)});const data=await p.evaluate(()=>{const banner=document.querySelector('.cookie-banner'),cta=document.querySelector('.hero-actions .button'),a=banner.getBoundingClientRect(),c=cta.getBoundingClientRect();return{height:a.height,overlap:a.left<c.right&&a.right>c.left&&a.top<c.bottom&&a.bottom>c.top,overflow:document.documentElement.scrollWidth>innerWidth,buttons:[...banner.querySelectorAll('button')].map(b=>{let r=b.getBoundingClientRect();return{height:r.height,visible:r.top>=a.top&&r.bottom<=a.bottom,width:r.width}})}});report.push({width,...data});assert.equal(data.overflow,false);if(mode==='after'){assert.equal(await p.locator('.cookie-banner button').evaluateAll(es=>es.every(e=>e.scrollWidth<=e.clientWidth)),true,'button text not clipped');assert.ok(data.buttons.every(b=>b.height>=44&&b.visible));if(width===1440)assert.equal(data.overlap,false);}
await p.locator('[data-consent=customize]').click();await p.screenshot({path:path.join(out,`dialog-${width}.png`)});assert.equal(await p.locator('.cookie-dialog button').count(),4);await p.locator('#cookie-analytics').focus();await p.keyboard.press('Tab');assert.equal(await p.locator('#cookie-advertising').evaluate(e=>e===document.activeElement),true);for(const action of ['accept','reject','save','close']){await p.keyboard.press('Tab');assert.equal(await p.locator('.cookie-dialog [data-consent='+action+']').evaluate(e=>e===document.activeElement),true);}await p.keyboard.press('Escape');assert.equal(await p.locator('[data-consent=customize]').evaluate(e=>e===document.activeElement),true);
if(mode==='after'){await p.setViewportSize({width,height:400});await p.locator('[data-consent=customize]').click();for(const button of await p.locator('.cookie-dialog button').all()){await button.focus();await button.scrollIntoViewIfNeeded();assert.equal(await button.isVisible(),true);}await p.keyboard.press('Escape');await p.addStyleTag({content:'html{font-size:200%}'});assert.equal(await p.locator('.cookie-banner').evaluate(e=>e.scrollWidth<=e.clientWidth),true,'consent zoom overflow');}
if(width===1440){await p.setViewportSize({width:1440,height:720});await p.goto('http://127.0.0.1:8769/');await p.screenshot({path:path.join(out,'banner-1440-short.png')});const overlap=await p.evaluate(()=>{const a=document.querySelector('.cookie-banner').getBoundingClientRect(),c=document.querySelector('.hero-actions .button').getBoundingClientRect();return a.left<c.right&&a.right>c.left&&a.top<c.bottom&&a.bottom>c.top});report.push({width:1440,viewportHeight:720,ctaOverlap:overlap});if(mode==='after')assert.equal(overlap,false);}
await ctx.close();}fs.writeFileSync(path.join(out,'metrics.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
