const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict'), http=require('node:http'), fs=require('node:fs'), path=require('node:path');
const root=path.resolve(__dirname,'..'), origin='http://127.0.0.1:8768', KEY='cw-consent-v1';
const real=process.env.CW_REAL_GA==='1';
const server=http.createServer((req,res)=>{let file=path.join(root,new URL(req.url,origin).pathname);if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
const stub=`const processCommand=c=>{if(window['ga-disable-G-RB6NSRRM9L'])return;if(c[0]==='config'){window.testConfig=c[2];document.cookie='_ga=test; path=/';document.cookie='_ga_RB6NSRRM9L=test; path=/';}if(c[0]==='event'){const data=new URLSearchParams({en:c[1],dl:window.testConfig.page_location,dr:window.testConfig.page_referrer,dt:window.testConfig.page_title,ep:JSON.stringify(c[2]||{})});fetch('https://www.google-analytics.com/g/collect?'+data,{method:'POST',keepalive:true});}};dataLayer.forEach(processCommand);dataLayer.push=(...cs)=>{cs.forEach(processCommand);return Array.prototype.push.apply(dataLayer,cs)};`;
async function main(){await new Promise(r=>server.listen(8768,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});let gaSource;
try{
const context=await browser.newContext();const requests=[],errors=[];let formStatus=200,formCount=0;
await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());
if(u.hostname==='127.0.0.1')return route.continue();
if(u.hostname==='challenges.cloudflare.com')return route.fulfill({contentType:'text/javascript',body:"const w=document.querySelector('.cf-turnstile');if(w){const i=document.createElement('input');i.type='hidden';i.name='cf-turnstile-response';w.append(i);}window.turnstile={reset(){document.querySelector('[name=cf-turnstile-response]').value=''}}"});
if(u.hostname==='formspree.io'){formCount++;return route.fulfill({status:formStatus,contentType:'application/json',body:formStatus===200?'{"ok":true}':'{"errors":[{"message":"Test"}]}'});}
requests.push({url:req.url(),body:req.postData()||''});
if(u.hostname==='www.googletagmanager.com'&&u.pathname==='/gtag/js'&&u.searchParams.get('id')==='G-RB6NSRRM9L'){
if(real&&!gaSource){const response=await route.fetch();assert.equal(response.status(),200);gaSource=await response.text();}
return route.fulfill({contentType:'text/javascript',body:real?gaSource:stub});}
// ALL collection, advertising, other tags and Stripe navigations are intercepted. No telemetry or payment leaves the test.
return route.fulfill({status:204,headers:{'access-control-allow-origin':'*'}});
});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
const gaRequests=()=>requests.filter(r=>/google-analytics|googletagmanager|doubleclick|googleadservices/.test(r.url));
const events=()=>requests.filter(r=>r.url.includes('/collect')).flatMap(r=>{const q=new URL(r.url).searchParams;const lines=r.body?r.body.split(/\r?\n/):[''];return lines.map(line=>{const combined=new URLSearchParams(q);for(const [k,v] of new URLSearchParams(line))combined.set(k,v);return Object.fromEntries(combined);});});
async function waitEvent(name,count){const deadline=Date.now()+(real?12000:1500);do{await page.waitForTimeout(150);}while(count>0&&events().filter(e=>e.en===name).length<count&&Date.now()<deadline);if(count===0)await page.waitForTimeout(real?1500:150);assert.equal(events().filter(e=>e.en===name).length,count,name+' count');}
async function manage(){await page.locator('[data-manage-cookies]').click();}
async function accept(){await page.locator('.cookie-banner [data-consent=accept]').click();await page.waitForTimeout(real?3000:300);}
async function fill(){await page.locator('#name').fill('PRIVATE_NAME');await page.locator('#company').fill('PRIVATE_COMPANY');await page.locator('#email').fill('private@example.org');for(let i=1;i<=3;i++)await page.locator('#url'+i).fill('https://secret.example.org/private');await page.locator('#message').fill('PRIVATE_MESSAGE');await page.locator('[name=cf-turnstile-response]').evaluate(e=>e.value='simulated-token');}
await page.goto(origin+'/?email=private@example.org#PRIVATE_HASH');await page.waitForTimeout(400);assert.equal(gaRequests().length,0);assert.equal((await context.cookies()).filter(c=>c.name.startsWith('_ga')).length,0);
await page.screenshot({path:path.join(process.env.TEMP||'/tmp','cw-consent-desktop.png')});
if(process.env.CW_AXE_PATH){await page.addScriptTag({path:process.env.CW_AXE_PATH});const audit=await page.evaluate(async()=>await axe.run(document.querySelector('.cookie-banner')));assert.deepEqual(audit.violations.map(v=>v.id),[]);}
await page.locator('.cookie-banner [data-consent=customize]').click();assert.equal(await page.locator('#cookie-analytics').isChecked(),false);await page.keyboard.press('Escape');assert.equal(await page.locator('.cookie-dialog').isVisible(),false);assert.equal(await page.locator('.cookie-banner [data-consent=customize]').evaluate(e=>e===document.activeElement),true);
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:850});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(process.env.TEMP||'/tmp','cw-consent-mobile.png')});await page.locator('.cookie-banner [data-consent=customize]').click();if(process.env.CW_AXE_PATH){const audit=await page.evaluate(async()=>await axe.run(document.querySelector('.cookie-dialog')));assert.deepEqual(audit.violations.map(v=>v.id),[]);}await page.screenshot({path:path.join(process.env.TEMP||'/tmp','cw-consent-settings.png')});await page.keyboard.press('Escape');
await page.locator('.cookie-banner [data-consent=reject]').click();await page.goto(origin+'/blog/');await page.reload();assert.equal(gaRequests().length,0);assert.equal(await page.locator('.cookie-banner').isVisible(),false);console.log('PASS A/B initial/ignored/customize/Escape/refusal/reload/navigation: no Google requests or GA cookies');
await page.goto(origin+'/?email=private@example.org#PRIVATE_HASH');await manage();await page.locator('#cookie-analytics').check();await page.locator('.cookie-dialog [data-consent=save]').click();await page.evaluate(()=>history.replaceState(null,'','/?email=PRIVATE_HISTORY#PRIVATE_FRAGMENT'));await waitEvent('page_view',1);assert.ok((await context.cookies()).some(c=>c.name==='_ga'),'GA cookie exists after acceptance');assert.equal(gaRequests().filter(r=>r.url.includes('/gtag/js')).length,1);
const frame=page.frames().find(f=>f.url().includes('analytics-frame.html'));const config=await frame.evaluate(()=>Array.from(dataLayer).map(c=>Array.from(c)).find(c=>c[0]==='config')[2]);assert.equal(config.send_page_view,false);assert.equal(config.allow_google_signals,false);assert.equal(config.allow_ad_personalization_signals,false);assert.equal(config.cookie_update,false);assert.equal(config.page_location,'https://changewatch.cybersignal.fr/');assert.equal(config.page_referrer,'');
await manage();await page.locator('.cookie-dialog [data-consent=accept]').click();await page.evaluate(()=>history.replaceState(null,'','/?email=PRIVATE_HISTORY#PRIVATE_FRAGMENT'));await waitEvent('page_view',1);
await page.locator('.hero-actions a[href="#tarifs"]').click();await waitEvent('commercial_cta_click',1);
// Keep the page open to inspect event delivery without starting Stripe checkout.
await page.evaluate(()=>document.querySelectorAll('a[href^="https://buy.stripe.com/"]').forEach(a=>a.addEventListener('click',e=>e.preventDefault())));
for(const plan of ['Starter','Business','Pro'])await page.getByRole('link',{name:'Choisir '+plan}).click();await waitEvent('stripe_click',3);assert.equal(events().some(e=>e.en==='purchase'),false);assert.deepEqual(events().filter(e=>e.en==='stripe_click').map(e=>real?e['ep.plan']:JSON.parse(e.ep).plan),['Starter','Business','Pro']);
const stripe=await page.locator('a[href^="https://buy.stripe.com/"]').evaluateAll(es=>es.map(e=>e.href));assert.deepEqual(stripe,['https://buy.stripe.com/dRm5kC8cA3P93hg9pc4gg02','https://buy.stripe.com/dRm28q50o2L5aJI58W4gg03','https://buy.stripe.com/3cI9AScsQ4Td8BA30O4gg04']);
formStatus=422;await fill();await page.locator('[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#form-status').dataset.state==='error');await waitEvent('generate_lead',0);
formStatus=200;await fill();await page.locator('[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#form-status').dataset.state==='success');await waitEvent('generate_lead',1);assert.equal(formCount,2);
assert.equal(JSON.stringify(requests).includes('PRIVATE_'),false);assert.equal(JSON.stringify(requests).includes('private%40'),false);assert.equal(JSON.stringify(requests).includes('secret.example.org'),false);assert.equal(decodeURIComponent(JSON.stringify(requests)).includes('private@example.org'),false);if(real)assert.ok(events().every(e=>e.tid==='G-RB6NSRRM9L'));assert.ok(requests.every(r=>['www.googletagmanager.com','www.google-analytics.com','region1.google-analytics.com'].includes(new URL(r.url).hostname)),'No advertising or unexpected destination');
await page.goto(origin+'/blog/veille-concurrentielle-ecommerce/?phone=PRIVATE_PHONE');await waitEvent('page_view',2);assert.equal(gaRequests().filter(r=>r.url.includes('/gtag/js')).length,2);console.log('PASS C/E/F/G one tag/page, page views, allowed CTA/plans, lead only after simulated 2xx, no PII in intercepted traffic');
// Share revocation across already open tabs, including removal of the loaded tag runtime.
const second=await context.newPage();await second.goto(origin+'/blog/');await second.waitForTimeout(real?3000:300);await manage();const beforeWithdrawal=gaRequests().length;await page.locator('.cookie-dialog [data-consent=reject]').click();await page.waitForTimeout(real?6000:500);assert.equal(gaRequests().length,beforeWithdrawal,'No request from the moment of withdrawal');assert.equal(page.frames().length,1);assert.equal(second.frames().length,1);assert.equal((await context.cookies()).filter(c=>c.name.startsWith('_ga')).length,0);const count=gaRequests().length;await page.reload();await second.reload();await page.waitForTimeout(real?2500:200);assert.equal(gaRequests().length,count);
await page.goto(origin+'/');await fill();await page.locator('[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#form-status').dataset.state==='success');assert.equal(gaRequests().length,count);console.log('PASS D withdrawal removes runtime/cookies, synchronizes tabs, persists after reload; refused successful form has no Analytics');
// Expired choice prompts again and fails closed.
await page.evaluate(key=>localStorage.setItem(key,JSON.stringify({version:1,analytics:true,expires:Date.now()-1})),KEY);await page.reload();assert.equal(await page.locator('.cookie-banner').isVisible(),true);assert.equal(gaRequests().length,count);
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('.cookie-banner [data-consent=customize]').click();await page.locator('#cookie-analytics').focus();await page.keyboard.press('Space');assert.equal(await page.locator('#cookie-analytics').isChecked(),true);await page.keyboard.press('Escape');assert.equal(gaRequests().length,count);
for(const route of ['/','/blog/','/blog/veille-concurrentielle-ecommerce/','/demo-produit.html','/cgv.html','/confidentialite.html','/mentions-legales.html']){await page.goto(origin+route);assert.equal(await page.locator('[data-manage-cookies]').count(),1);if(await page.locator('.cookie-banner').isVisible())await page.locator('.cookie-banner [data-consent=reject]').click();}
assert.deepEqual(errors,[]);await context.close();
const blocked=await browser.newContext();await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError')}})});await blocked.route('https://**/*',r=>r.fulfill({status:204}));const bp=await blocked.newPage();await bp.goto(origin);await bp.locator('.cookie-banner [data-consent=reject]').click();assert.equal(await bp.locator('.cookie-banner').isVisible(),false);await bp.reload();assert.equal(await bp.locator('.cookie-banner').isVisible(),true);await blocked.close();
assert.deepEqual([...new Set(events().map(e=>e.en))].sort(),['commercial_cta_click','generate_lead','page_view','stripe_click']);
console.log('Observed event names: '+[...new Set(events().map(e=>e.en))].join(', '));
console.log('PASS H seven management links, keyboard, responsive, expiry, blocked storage, no page errors');console.log(real?'REAL Google tag; ALL collection intercepted, no telemetry sent':'Deterministic tag stub; ALL services simulated');
}finally{await browser.close();server.close();}}
main().catch(e=>{console.error(e);server.close();process.exitCode=1});
